# Generated by Django 4.2.1 on 2023-11-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Pez', 'Pez'), ('Pájaro', 'Pájaro'), ('Conejo', 'Conejo'), ('Hamster', 'Hamster'), ('Cobaya', 'Cobaya'), ('Reptil', 'Reptil'), ('Conejillo de Indias', 'Conejillo de Indias'), ('Hurón', 'Hurón'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
