# Generated by Django 4.2.1 on 2023-11-17 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_solicituddecuidado_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GananciaPorSolicitud',
            fields=[
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.solicituddecuidado')),
                ('monto_ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
