# Generated by Django 4.2.1 on 2023-10-05 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_admin_alter_user_is_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDeCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('cuidadores_aceptan', models.ManyToManyField(related_name='solicitudes_aceptadas', to='account.cuidador')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.propietario')),
                ('tipo_de_cuidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tipodecuidado')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cuidador')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.propietario')),
                ('solicitud_de_cuidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.solicituddecuidado')),
            ],
        ),
    ]
