# Generated by Django 4.2.1 on 2023-11-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_mascota_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddecuidado',
            name='tipo_de_cuidado',
            field=models.CharField(choices=[('Alojamiento', 'Alojamiento'), ('Cuidado', 'Cuidado'), ('Paseo', 'Paseo'), ('Guardería', 'Guardería'), ('Peluquería', 'Peluquería'), ('Taxi', 'Taxi')], max_length=20),
        ),
    ]
