# Generated by Django 4.2.1 on 2023-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_solicituddecuidado_tipo_de_cuidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddecuidado',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicituddecuidado',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
