# Generated by Django 4.2.1 on 2023-11-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_solicituddecuidado_tipo_de_cuidado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddecuidado',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
    ]
