# Generated by Django 4.2.1 on 2023-11-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_solicituddecuidado_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
