# Generated by Django 4.2.3 on 2023-11-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_cuidador_latitud_cuidador_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddecuidado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
